from env.mota_builder import MotaBuilder


def map02() -> MotaBuilder:
    builder = MotaBuilder()
    builder.reset()
    builder.set_player((0, 1), 2700, 10, 10, 0, 0)
    builder.add_enemy_template('greenSlime', 50, 14, 5)
    builder.add_enemy_template('redSlime', 80, 13, 6)
    builder.add_enemy_template('bat', 30, 20, 4)
    builder.add_enemy_template('skeleton', 60, 18, 10)
    builder.add_enemy_template('bluePriest', 100, 22, 15)
    builder.add_enemy_template('blackSlime', 120, 25, 13)
    builder.add_enemy_template('yellowGuard', 30, 20, 17)
    builder.add_item_template('redPotion', 150, 0, 0, 0, 0)
    builder.add_item_template('redJewel', 0, 2, 0, 0, 0)
    builder.add_item_template('blueJewel', 0, 0, 2, 0, 0)
    builder.add_item_template('yellowKey', 0, 0, 0, 1, 0)
    builder.add_item_template('blueKey', 0, 0, 0, 0, 1)
    builder.add_item_template('yellowDoor', 0, 0, 0, -1, 0)
    builder.add_item_template('blueDoor', 0, 0, 0, 0, -1)
    builder.add_event((1, 1), 'greenSlime')
    builder.add_event((1, 2), 'yellowDoor')
    builder.add_event((1, 3), 'greenSlime')
    builder.add_event((2, 1), 'yellowKey')
    builder.add_event((2, 2), 'redSlime')
    builder.add_event((2, 3), 'redJewel')
    builder.add_event((2, 4), 'redPotion')
    builder.add_event((3, 1), 'bat')
    builder.add_event((3, 2), 'yellowDoor')
    builder.add_event((3, 3), 'redPotion')
    builder.add_event((3, 4), 'redJewel')
    builder.add_event((3, 5), 'redPotion')
    builder.add_event((3, 6), 'redSlime')
    builder.add_event((3, 7), 'greenSlime')
    builder.add_event((4, 1), 'blueJewel')
    builder.add_event((4, 2), 'skeleton')
    builder.add_event((4, 3), 'yellowKey')
    builder.add_event((4, 4), 'bat')
    builder.add_event((4, 5), 'yellowDoor')
    builder.add_event((5, 1), 'yellowKey')
    builder.add_event((5, 2), 'redPotion')
    builder.add_event((5, 3), 'blueJewel')
    builder.add_event((5, 4), 'bluePriest')
    builder.add_event((5, 5), 'blueJewel')
    builder.add_event((5, 6), 'blackSlime')
    builder.add_event((5, 7), 'skeleton')
    builder.add_event((6, 1), 'redPotion')
    builder.add_event((6, 2), 'blueDoor')
    builder.add_event((6, 3), 'redJewel')
    builder.add_event((7, 1), 'redJewel')
    builder.add_event((7, 2), 'blueJewel')
    builder.add_event((7, 3), 'yellowGuard')
    builder.add_event((7, 4), 'redPotion')
    builder.add_event((8, 1), 'bluePriest')
    builder.add_event((8, 2), 'redPotion')
    builder.add_event((8, 3), 'redPotion')
    builder.add_event((8, 5), 'blueKey')
    builder.add_event((10, 1), 'redSlime')
    builder.add_event((10, 2), 'redPotion')
    builder.add_event((11, 1), 'yellowKey')
    builder.add_event((11, 3), 'yellowDoor')
    builder.add_event((11, 4), 'yellowKey')
    builder.add_event((13, 1), 'yellowDoor')
    builder.set_end((14, 1))
    builder.add_event((14, 2), 'redJewel')
    builder.add_links((0, 1), (1, 1), (1, 2), (1, 3))
    builder.add_links((1, 1), (2, 1))
    builder.add_links((1, 2), (2, 2))
    builder.add_links((1, 3), (2, 3), (2, 4))
    builder.add_links((2, 1), (3, 1), (3, 2))
    builder.add_links((2, 2), (3, 3), (3, 4))
    builder.add_links((2, 2), (3, 4), (3, 5))
    builder.add_links((2, 3), (3, 6))
    builder.add_links((2, 4), (3, 7))
    builder.add_links((3, 1), (4, 1))
    builder.add_links((3, 2), (4, 2))
    builder.add_links((3, 6), (4, 3))
    builder.add_links((3, 7), (4, 4))
    builder.add_links((3, 7), (4, 5))
    builder.add_links((4, 2), (5, 1), (5, 2))
    builder.add_links((4, 2), (5, 2), (5, 3))
    builder.add_links((4, 3), (4, 4), (5, 4))
    builder.add_links((4, 5), (5, 5), (5, 6), (5, 7))
    builder.add_links((5, 4), (6, 1))
    builder.add_links((5, 6), (6, 2), (8, 1))
    builder.add_links((5, 7), (6, 3))
    builder.add_links((6, 1), (7, 1))
    builder.add_links((6, 2), (7, 2), (7, 3))
    builder.add_links((6, 3), (7, 4))
    builder.add_links((7, 1), (8, 1))
    builder.add_links((7, 2), (8, 2))
    builder.add_links((7, 2), (8, 3))
    builder.add_links((7, 3), (10, 1), (10, 2))
    builder.add_links((7, 4), (8, 5))
    builder.add_links((10, 1), (11, 1))
    builder.add_links((10, 1), (11, 3), (13, 1))
    builder.add_links((10, 2), (11, 3), (11, 4))
    builder.add_links((13, 1), (14, 1), (14, 2))
    return builder
